// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC851de67vfzFYC99bmVuI-ON8Cj23rWzQ',
    appId: '1:766303790765:web:7c5d7e6b2ba5327b738824',
    messagingSenderId: '766303790765',
    projectId: 'do-an-web-7e477-2147b',
    authDomain: 'do-an-web-7e477-2147b.firebaseapp.com',
    storageBucket: 'do-an-web-7e477-2147b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi8BK1qNjsQ2LXz00uGLfUc2EPSvUGzWU',
    appId: '1:766303790765:android:cc30a635273de940738824',
    messagingSenderId: '766303790765',
    projectId: 'do-an-web-7e477-2147b',
    storageBucket: 'do-an-web-7e477-2147b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbk-Q_mSm90aG4up-DwXQYgGv7s5ZEpXA',
    appId: '1:766303790765:ios:a57566a844b8e49b738824',
    messagingSenderId: '766303790765',
    projectId: 'do-an-web-7e477-2147b',
    storageBucket: 'do-an-web-7e477-2147b.appspot.com',
    iosBundleId: 'com.example.doAn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbk-Q_mSm90aG4up-DwXQYgGv7s5ZEpXA',
    appId: '1:766303790765:ios:d7f5a1e3fa7ee817738824',
    messagingSenderId: '766303790765',
    projectId: 'do-an-web-7e477-2147b',
    storageBucket: 'do-an-web-7e477-2147b.appspot.com',
    iosBundleId: 'com.example.doAn.RunnerTests',
  );
}
